<a href="https://colab.research.google.com/github/sebekpro/python-ds/blob/main/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* @author: krakowiakpawel9@gmail.com  
* @site: e-smartdata.org

### NumPy
>Strona biblioteki: [https://numpy.org/](https://numpy.org/)  
>Dokumentacja: [https://numpy.org/doc/](https://numpy.org/doc/)  
>
>Podstawowa biblioteka do obliczeń numerycznych w języku Python.
>
>Aby zainstalować bibliotekę NumPy, użyj polecenia poniżej:
```
pip install numpy
```

### Spis treści:
1. [Podstawy](#a1)
2. [Typy danych](#a2)
3. [Tworzenie tablic](#a3)
4. [Podstawowe operacje na tablicach](#a4)
5. [Generowanie liczb pseudolosowych](#a5)
6. [Podstawowe funkcje](#a6)
7. [Indeksowanie, Wycinanie](#a7)
8. [Iteracja po tablicach](#a8)
9. [Zmiana rozmiaru tablic](#a9)
10. [Maski logiczne](#a10)


### <a name='a1'></a> Podstawy

In [2]:
import numpy as np
np.__version__

'1.26.4'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1D Array

In [ ]:
x = np.array([1, 3])
x

array([1, 3])

In [ ]:
print(x)

[1 3]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [ ]:
x.dtype

dtype('float64')

2D Array

In [ ]:
x = np.array([[1, 2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x = np.array([[1, 2, 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [ ]:
x.shape

(2, 3)

3D Array

In [ ]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],

     [[4, 1, 3],
      [4, 2, 1]],

     [[3, 2, 1],
      [4, 3, 2]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [ ]:
x.ndim

3

In [ ]:
x.shape

(3, 2, 3)

### <a name='a2'></a> Typy danych

In [ ]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [ ]:
A = np.array([1.0, 2.3, 3.3])
A.dtype

dtype('float64')

In [ ]:
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

In [ ]:
A = np.array([1, 2, 3], dtype='complex')
A.dtype

dtype('complex128')

In [ ]:
A = np.array([1.0, 2.7, 3.3], dtype='int')
A.dtype

dtype('int64')

In [ ]:
A

array([1, 2, 3])

In [ ]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [2]:
A = np.array([24, 120, 230], dtype=np.int16)
A.dtype

dtype('int16')

In [ ]:
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype

dtype('uint8')

### <a name='a3'></a> Tworzenie tablic

In [ ]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape=(5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.ones(shape=(5, 5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.full(shape=(3, 3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [18]:
np.arange(start=1000, stop=100, step=-100)

array([1000,  900,  800,  700,  600,  500,  400,  300,  200])

In [ ]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [ ]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [23]:
np.linspace(start=0, stop=1, num=3)

array([0. , 0.5, 1. ])

In [4]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
A.reshape((5, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [37]:
A.reshape((-1, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### <a name='a4'></a> Podstawowe operacje na tablicach

In [9]:
A = np.array([3, 1, 4, -2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[ 3  1  4 -2]
[ 3 -1  3  2]


In [10]:
A + B

array([6, 0, 7, 0])

In [11]:
A - B

array([ 0,  2,  1, -4])

In [12]:
A * B

array([ 9, -1, 12, -4])

In [13]:
A / B

array([ 1.        , -1.        ,  1.33333333, -1.        ])

In [23]:
np.add(A, B)

array([6, 0, 7, 0])

In [24]:
np.subtract(A, B)

array([ 0,  2,  1, -4])

In [25]:
np.multiply(A, B)

array([ 9, -1, 12, -4])

In [26]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333, -1.        ])

In [14]:
A + 3

array([6, 4, 7, 1])

In [15]:
2 * A

array([ 6,  2,  8, -4])

In [16]:
A + 3*B

array([12, -2, 13,  4])

In [27]:
print("A = ", A);
print("B = ", B);
print(np.subtract(A, B));

A =  [ 3  1  4 -2]
B =  [ 3 -1  3  2]
[ 0  2  1 -4]


In [28]:
X = np.array([[1, 3], [-2, 10]])
Y = np.array([[6, 0], [-1, 20]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2 10]] 

[[ 6  0]
 [-1 20]]


In [29]:
X * Y

array([[  6,   0],
       [  2, 200]])

In [30]:
np.dot(X, Y)

array([[  3,  60],
       [-22, 200]])

In [32]:
X.dot(Y)

array([[  3,  60],
       [-22, 200]])

In [34]:
Y.dot(X)

array([[  6,  18],
       [-41, 197]])

In [35]:
X @ Y

array([[  3,  60],
       [-22, 200]])

### <a name='a5'></a>  Generowanie liczb pseudolosowych

In [4]:
np.random.seed(0)

In [5]:
np.random.randn()

1.764052345967664

In [ ]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [ ]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [6]:
np.random.rand()

0.6027633760716439

In [7]:
np.random.rand(10)

array([0.54488318, 0.4236548 , 0.64589411, 0.43758721, 0.891773  ,
       0.96366276, 0.38344152, 0.79172504, 0.52889492, 0.56804456])

In [8]:
np.random.rand(10, 2)

array([[0.92559664, 0.07103606],
       [0.0871293 , 0.0202184 ],
       [0.83261985, 0.77815675],
       [0.87001215, 0.97861834],
       [0.79915856, 0.46147936],
       [0.78052918, 0.11827443],
       [0.63992102, 0.14335329],
       [0.94466892, 0.52184832],
       [0.41466194, 0.26455561],
       [0.77423369, 0.45615033]])

In [17]:
np.random.randint(20)

6

In [18]:
np.random.randint(low=10, high=101)

27

In [34]:
np.random.randint(low=10, high=150, size=111)

array([ 24,  71,  97,  66, 107,  56, 118,  82, 130,  12,  27,  95, 103,
       111, 130,  17,  65,  36, 142, 119,  99,  36, 121,  93,  88, 131,
       106, 101,  46, 112, 137, 141,  61,  59,  41,  22, 121, 108,  81,
       104,  55,  75,  98,  26,  55, 137,  14,  50, 148,  88, 112,  14,
        25,  39,  32, 120,  53, 140, 135, 130, 138, 105, 120,  96,  56,
        99,  72,  47, 129,  69,  93,  50, 114, 131,  99,  39,  38,  62,
        52, 148,  27, 138,  48,  58,  55, 132,  32, 102,  75,  95,  76,
        42,  80, 112, 132,  92, 112,  99,  89, 123,  95,  11,  19, 125,
        91, 149,  74,  77,  64,  46, 136])

In [36]:
np.random.choice([4, 2, 1, 3, 5])

5

In [38]:
np.random.choice(['python', 'java', 'sql'])

'sql'

In [41]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.random.shuffle(data)

In [51]:
data

array([4, 2, 6, 7, 9, 5, 8, 3, 0, 1])

### <a name='a6'></a> Podstawowe funkcje

In [53]:
np.exp(1)

2.718281828459045

In [55]:
np.sqrt(16)

4.0

In [70]:
np.all([2, 3, 1])

True

In [78]:
np.any([0, 0, 0])

False

In [79]:
bool(1.3)

True

In [84]:
A = np.random.rand(5)
A

array([0.42600239, 0.89270716, 0.10357846, 0.01809636, 0.59058538])

In [85]:
np.argmax(A)

1

In [86]:
A[np.argmax(A)]

0.8927071642489816

In [87]:
np.argmin(A)

3

In [88]:
np.argsort(A)

array([3, 2, 0, 4, 1])

In [89]:
np.max(A)

0.8927071642489816

In [90]:
np.min(A)

0.01809635820147515

In [91]:
np.mean(A)

0.4061939505232647

In [92]:
np.median(A)

0.42600238766956056

In [93]:
np.std(A)

0.3204008596770041

###  <a name='a7'></a> Indeksowanie, Wycinanie

In [71]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
# A[idx], A[start:stop], A[:stop], A[start:]

In [72]:
A[2]

2

In [73]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [74]:
A[:2]
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [75]:
A[[0, 2]]

array([0, 2])

In [76]:
A[-1]

19

In [77]:
A[10:15]

array([10, 11, 12, 13, 14])

In [78]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [79]:
# A[1:3, 1:4]
A[1,2] = 77
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 77,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [80]:
A[1, 2] = 77
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 77,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### <a name='a8'></a> Iteracja po tablicach

In [81]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 77,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [44]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [45]:
for row in A:
    print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [46]:
for item in A.flat:
    print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


### <a name='a9'></a> Zmiana rozmiaru tablic

In [47]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [48]:
A.shape

(4, 5)

In [49]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [53]:
A.ravel()


array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [54]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

### <a name='a10'></a> Maski logiczne

In [57]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [63]:
A[A<0]
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [64]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [65]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [66]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])